### ISSUE TITLE
Melpa?

### ISSUE THREAD

**Issue by mcampbell** [mvarela/Sunburn-Theme#1]
Any chance of getting this in a package repo?

**Comment by mvarela** [comment]
Hi,
  I haven't looked into how to do this yet, but it should be doable. I'll have a look.

**Comment by mvarela** [comment]
Just submitted a pull request to Melpa.

**Comment by mvarela** [comment]
It's now in MELPA. Enjoy!

**Comment by mcampbell** [comment]
Just pulled it from there; very nice, thanks!

**Comment by mvarela** [comment]
You're welcome!
