### ISSUE TITLE
Links in Emacs Buffer

### ISSUE THREAD

**Issue by ajakk** [mvarela/Sunburn-Theme#3]
Perhaps this is an error which I am at fault for, but links in Sunburn look no different than other text in the Emacs buffer, while the default Emacs theme shows it explicitly.

Compare the [Emacs theme main page](https://i.imgur.com/jeqcPVL.png) to [Sunburn's main page](https://i.imgur.com/n20aKm0.png).

Is it possible to change this so that links are more obvious?

**Comment by mvarela** [comment]
The links are shown as underlined, not in different color. However, they are colored in Org mode, so I guess it is inconsistent. I'll make them the same color.
It seems, however, that those examples are not just links, as the link face is already colored differently (e.g., if you use `org-mode` links or `eww`). I'll have to check what they are exactly, so I can define them properly.

**Comment by mvarela** [comment]
I've just checked by loading a vanilla emacs instance without any config, and loading sunburn directly, and the links show up as yellow, as they should. Still on my spacemacs main buffer they show as white, so there's probably another face in use there. I can't, however, reproduce your condition.
You can see screen captures [here](https://imgur.com/a/5Lpz0)

**Comment by mvarela** [comment]
I've recolored the `button` face, and added a definition for `widget-button-face` which was missing (and it's the one used on the Spacemacs opening buffer). Please check whether this fixes your issue, and if not, put your cursor over the text where the color is wrong, and do `M-x describe-face`, to see which face it is, so it can be modified.

**Comment by ajakk** [comment]
Thanks, the new commit fixed it!

**Comment by mvarela** [comment]
Glad to hear!
