### ISSUE TITLE
Magit colors

### ISSUE THREAD

**Issue by Wasabichicken** [mvarela/Sunburn-Theme#4]
Hi, and thank you for a neat little theme. :)

I wonder if you have tested this theme with https://magit.vc/, and if so, if you like the colors being used there. If you haven't, then I would like to suggest that the chunk selection highlight color in the Magit status window be changed from the (rather contrasting IMHO) blue into a more neutral grey, preferably only slightly brighter than the ordinary (non-highlighted) grey background.

It's something that I think Zenburn does correctly. When looking at diffs/chunks, I prefer to only have the red/green diff lines stand out and the rest be more neutral colors.

**Comment by mvarela** [comment]
Hi,
  I'm not sure which case is exactly the one you're referring to, but I guess it was the face for magit-diff-highlight, which was set to bg+05, which is that stronger blue. It seems that in Zenburn, the foreground is also hard-coded. I've modified it now so it's slightly different (both fg and bg slightly muted).
Here are a couple of screenshots with the changes.
![screen shot 2017-11-01 at 20 18 05](https://user-images.githubusercontent.com/112811/32290563-24822980-bf43-11e7-812a-34e5419efb55.png)
![screen shot 2017-11-01 at 20 20 41](https://user-images.githubusercontent.com/112811/32290565-24af83d0-bf43-11e7-8f8e-2277e3d84941.png)

Let me know if this is along the lines you were thinking :)

**Comment by Wasabichicken** [comment]
Nailed it. That is _precisely_ along the lines I'm thinking!

**Comment by mvarela** [comment]
Excellent!
